In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn import datasets

In [3]:
df=sns.load_dataset('penguins')

In [4]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [7]:
df.shape

(344, 7)

In [8]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [9]:
df.dropna(inplace=True)

In [10]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [12]:
Sex=pd.get_dummies(df['sex'],drop_first=True)
Sex.head()

Male
0     1
1     0
2     0
4     0
5     1

In [13]:
Island=pd.get_dummies(df['island'],drop_first=True)
Island.head()

Dream  Torgersen
0      0          1
1      0          1
2      0          1
4      0          1
5      0          1

In [14]:
newdata=pd.concat([df,Sex,Island],axis=1)
newdata.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  Male  Dream  Torgersen  
0       3750.0    Male     1      0          1  
1       3800.0  Female     0      0          1  
2       3250.0  Female     0      0          1  
4       3450.0  Female     0      0          1  
5       3650.0    Male     1      0          1

In [15]:
newdata.drop(['sex','island'],axis=1,inplace=True)
newdata.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0  Adelie            39.1           18.7              181.0       3750.0   
1  Adelie            39.5           17.4              186.0       3800.0   
2  Adelie            40.3           18.0              195.0       3250.0   
4  Adelie            36.7           19.3              193.0       3450.0   
5  Adelie            39.3           20.6              190.0       3650.0   

   Male  Dream  Torgersen  
0     1      0          1  
1     0      0          1  
2     0      0          1  
4     0      0          1  
5     1      0          1

In [22]:
Y=newdata.species

In [23]:
Y.unique()

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [24]:
y=Y.map({'Adelie':0,'Chinstrap':1,'Gentoo':2})
y.head()

0    0
1    0
2    0
4    0
5    0
Name: species, dtype: int64

In [25]:
newdata.drop('species',inplace=True,axis=1)

In [26]:
newdata.head()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  Male  Dream  \
0            39.1           18.7              181.0       3750.0     1      0   
1            39.5           17.4              186.0       3800.0     0      0   
2            40.3           18.0              195.0       3250.0     0      0   
4            36.7           19.3              193.0       3450.0     0      0   
5            39.3           20.6              190.0       3650.0     1      0   

   Torgersen  
0          1  
1          1  
2          1  
4          1  
5          1

In [27]:
x=newdata

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [29]:
from sklearn.ensemble import RandomForestClassifier
Classifier=RandomForestClassifier(n_estimators=5,criterion='entropy',random_state=0)
Classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

In [30]:
y_predict=Classifier.predict(x_test)
y_predict

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 0, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2], dtype=int64)

In [31]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,accuracy_score

In [33]:
cm=confusion_matrix(y_test,y_predict)
print(cm)

[[48  0  0]
 [ 1 15  0]
 [ 1  0 35]]


In [34]:
accuracy_score(y_test,y_predict)

0.98

In [35]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        48
           1       1.00      0.94      0.97        16
           2       1.00      0.97      0.99        36

    accuracy                           0.98       100
   macro avg       0.99      0.97      0.98       100
weighted avg       0.98      0.98      0.98       100

